### ISSUE TITLE
Binaries of latest version

### ISSUE THREAD

**Issue by mathiasbockwoldt** [rescribe/bookpipeline#1]
Thank you for the tool!

On the website, the linked binaries are still version 1.0.0. Is it possible to update the downloadable binaries to 1.1.0?

**Comment by nickjwhite** [comment]
Hi @mathiasbockwoldt, sorry, I don't know how I missed releasing binaries for this version! I have just done that now, and keep an eye out as I'm preparing a new release in the next few days :)

**Comment by nickjwhite** [comment]
Just a note here to say the new release is out, v1.2.0, please let me know here or anywhere else if you find any issues with it!
